[#work-experience]
== Experiencia Laboral

Mar 2022 - Actualidad:: **Site Reliability Engineer**
__https://etermax.com/[Etermax]__
Diseño e implementación de plataformas Kubernetes. Implementación de herramientas de integración continua y entrega continua.
Sep 2021 - Dic 2021:: **Ayudante de Cátedra A**
__https://www.uns.edu.ar/[Universidad Nacional del Sur]__ Cargo en la asignatura "Sistemas Operativos".
Feb 2021 - Feb 2022:: **Containers & DevOps Content Developer**
__https://www.redhat.com/[Red Hat]__
Diseño y desarrollo de contenido para currícula de capacitación técnica en los productos de la empresa. 
Jul 2018 - Ene 2021:: **DevOps Engineer**
__https://www.avature.net/[Avature]__
Diseño, desarrollo e implementación de infrastructura para gestión de configuraciones. Implementación de herramientas de integración continua y entrega continua. Mentoreo a equipos de desarrollo en la definición de sus necesidades de infrastructura.
Dic 2014 - Jun 2018:: **Senior System Engineer**
__https://www.avature.net/[Avature]__
Planificación, implementación y mantenimiento de servidores en la nube, parte de la infrastructura de la empresa. Monitoreo del comportamiento de los sistemas en tiempo real. Asegurar la alta disponibilidad de los servicios críticos para cumplir son los SLA. 
Ene 2009 - Nov 2014:: **System / Network Administrator**
__https://cooperativaobrera.coop/[Cooperativa Obrera Ltda.]__
Planificación, implementación y mantenimiento de servicios en servidores parte de la infrastructura de la empresa. Monitoreo del comportamiento de los sistemas en tiempo real. Asegurar la alta disponibilidad de los servicios críticos.
Dic 2002 - Dic 2008:: **Software Developer**
__https://cooperativaobrera.coop/[Cooperativa Obrera Ltda.]__
Diseño, desarrollo, testeo e implementación de un sistema de punto de venta (PoS), basado en Linux / C++. Instalación, configuración y mantenimiento de servidores Linux.
Sep 2002 - Nov 2002:: **Technical Support Enginner**
__http://www.pullman.com.ar/[Garcia Navarro & Cia. S.A.]__
Soporte técnico de primer nivel. Planificación y despliegue de una red de área local en oficina anexa.
Ene 2002 - May 2002:: **Network Architect Intern**
__https://www.slb.com/[Schlumberger]__
Pasantía. Parte de _OFS IT Architecture Team_. Análisis y modelado del comportamiento de aplicaciones sobre redes de área amplia (WAN).
Feb 2001 - Dic 2001:: **Ayudante de Cátedra B**
__https://www.uns.edu.ar/[Universidad Nacional del Sur]__ Cargo en las asignaturas "Resolución de Problemas y Algoritmos" y "Estructuras de Datos y Algoritmos".