name: Render Asciidoc Files
on:
  push:
    branches:
      - main
    paths:
      - "**.adoc"
jobs:
  adoc_build:
    runs-on: ubuntu-latest
    name: Asciidoctor cv_en.adoc
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@v2
        with:
          asciidoctor_params: --attribute=nofooter
          ebook_main_adoc_file: cv_en
          pdf_build: true
          slides_build: false
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v2
        with:
          name: EN CV
          path: ebook.pdf
