name: Render Asciidoc Files
on:
  push:
    branches:
      - main
    paths:
      - "**.adoc"
jobs:
  adoc_build:
    runs-on: ubuntu-latest
    name: Asciidoctor cv_en.adoc
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build container
        id: adocbuild
        uses: tonynv/asciidoctor-action@master
        with:
          program: "asciidoctor --backend=pdf cv_en.adoc"
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v2
        with:
          name: EN CV
          path: cv_en.pdf
